name: 'weather_dbt'
version: '1.0.0'
config-version: 2

profile: 'weather_dbt'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  weather_dbt:
    stg:
      +materialized: view
    marts:
      +materialized: table
      fct_weather:
        +description: "Modèle d'exposition pour le dashboard"