weather_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost       # Ou 'postgres' si dbt est exécuté dans Docker
      user: postgres
      pass: postgres
      port: 5432
      dbname: data_warehouse
      schema: public
      threads: 4
