version: 2

models:
  - name: fct_weather
    description: "Table de faits contenant les relevés météo horaires enrichis des agrégats quotidiens."
    columns:
      - name: city
        description: "Nom de la ville."
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Nantes', 'Paris', 'Dublin']

      - name: fetched_at
        description: "Horodatage UTC du relevé."
        tests:
          - not_null

      - name: temperature_celsius
        description: "Température mesurée en degrés Celsius."
        tests:
          - not_null